# Generated by Django 3.0.2 on 2020-02-09 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='payload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deals.Payload'),
        ),
        migrations.AddField(
            model_name='response',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deals.Request'),
        ),
        migrations.AddField(
            model_name='request',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='payload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deals.Payload'),
        ),
        migrations.AddField(
            model_name='request',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
