# Generated by Django 3.0.2 on 2020-02-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20200209_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='to_user',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='from_user',
            new_name='sender',
        ),
    ]
